# Generated by Django 5.2.5 on 2025-09-25 18:21

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Nombre único para la categoría (ej. Pizzas, Pastas, Bebidas)', max_length=100, unique=True, verbose_name='Nombre de la Categoría')),
                ('descripcion', models.TextField(blank=True, help_text='Descripción opcional de la categoría', verbose_name='Descripción')),
                ('imagen', models.ImageField(blank=True, help_text='Imagen representativa de la categoría', null=True, upload_to='categorias/', verbose_name='Imagen de la Categoría')),
                ('activo', models.BooleanField(default=True, help_text='Si está activo, la categoría se mostrará en el menú', verbose_name='Activo')),
                ('orden', models.PositiveIntegerField(default=0, help_text='Número para ordenar las categorías (menor número = mayor prioridad)', verbose_name='Orden de Visualización')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, verbose_name='Última Actualización')),
            ],
            options={
                'verbose_name': 'Categoría',
                'verbose_name_plural': 'Categorías',
                'ordering': ['orden', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='Platillo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Nombre completo del platillo', max_length=200, verbose_name='Nombre del Platillo')),
                ('descripcion', models.TextField(help_text='Descripción detallada del platillo, ingredientes, etc.', verbose_name='Descripción')),
                ('precio', models.DecimalField(decimal_places=2, help_text='Precio en euros (€)', max_digits=8, validators=[django.core.validators.MinValueValidator(0.01)], verbose_name='Precio')),
                ('precio_oferta', models.DecimalField(blank=True, decimal_places=2, help_text='Precio promocional (opcional)', max_digits=8, null=True, validators=[django.core.validators.MinValueValidator(0.01)], verbose_name='Precio de Oferta')),
                ('tamaño', models.CharField(choices=[('pequeño', 'Pequeño'), ('mediano', 'Mediano'), ('grande', 'Grande'), ('familiar', 'Familiar')], default='mediano', help_text='Tamaño del platillo', max_length=20, verbose_name='Tamaño')),
                ('imagen', models.ImageField(blank=True, help_text='Foto del platillo', null=True, upload_to='platillos/', verbose_name='Imagen del Platillo')),
                ('ingredientes', models.TextField(blank=True, help_text='Lista de ingredientes principales', verbose_name='Ingredientes')),
                ('calorias', models.PositiveIntegerField(blank=True, help_text='Calorías aproximadas por porción', null=True, verbose_name='Calorías')),
                ('tiempo_preparacion', models.PositiveIntegerField(default=15, help_text='Tiempo en minutos para preparar el platillo', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(120)], verbose_name='Tiempo de Preparación')),
                ('disponible', models.BooleanField(default=True, help_text='Si el platillo está disponible para pedidos', verbose_name='Disponible Hoy')),
                ('activo', models.BooleanField(default=True, help_text='Si está activo, el platillo aparece en el menú', verbose_name='Activo en Menú')),
                ('destacado', models.BooleanField(default=False, help_text='Marcar para mostrar en sección destacados', verbose_name='Platillo Destacado')),
                ('vegetariano', models.BooleanField(default=False, help_text='Platillo apto para vegetarianos', verbose_name='Vegetariano')),
                ('vegano', models.BooleanField(default=False, help_text='Platillo apto para veganos', verbose_name='Vegano')),
                ('sin_gluten', models.BooleanField(default=False, help_text='Platillo libre de gluten', verbose_name='Sin Gluten')),
                ('picante', models.BooleanField(default=False, help_text='Platillo con nivel de picante', verbose_name='Picante')),
                ('valoracion', models.DecimalField(decimal_places=2, default=0.0, help_text='Valoración promedio de los clientes (0-5 estrellas)', max_digits=3, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(5.0)], verbose_name='Valoración Promedio')),
                ('numero_valoraciones', models.PositiveIntegerField(default=0, help_text='Total de valoraciones recibidas', verbose_name='Número de Valoraciones')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, verbose_name='Última Actualización')),
                ('categoria', models.ForeignKey(help_text='Categoría a la que pertenece este platillo', on_delete=django.db.models.deletion.CASCADE, related_name='platillos', to='platillos.categoria', verbose_name='Categoría')),
            ],
            options={
                'verbose_name': 'Platillo',
                'verbose_name_plural': 'Platillos',
                'ordering': ['-destacado', 'categoria', 'nombre'],
                'indexes': [models.Index(fields=['categoria', 'activo'], name='platillos_p_categor_026771_idx'), models.Index(fields=['destacado', 'activo'], name='platillos_p_destaca_536aae_idx'), models.Index(fields=['precio'], name='platillos_p_precio_4bca5e_idx')],
            },
        ),
    ]
